1D

In [ ]:
import numpy as np
b = np.array([1,2,3])
print(b.ndim)
print(b.shape)

1
(3,)


2D

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c.ndim)
print(c.shape)


[1 2 3]
2
(2, 3)


3D

In [ ]:
c = np.array([[
    [0,1]],
    [[0,1]]]
             )
print(c.ndim)
print(c.shape)

print('Another example')
d = np.array([[
    [1,2]],
    [[2,3]
]])
print(d.ndim)
print(d.shape)


3
(2, 1, 2)
Another example
3
(2, 1, 2)


In [ ]:
e = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
])
print(e.ndim)
print(e.shape)

3
(1, 2, 3)


| Axis | Meaning          | Size |
| ---- | ---------------- | ---- |
| 0    | Number of layers | 1    |
| 1    | Rows per layer   | 2    |
| 2    | Columns per row  | 3    |


**Reshape**

In [ ]:
a = np.arange(9).reshape(3,3)
print(a.ndim)
print(a)

2
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**itemsize**

In [ ]:
print(a.itemsize)
print(a.nbytes)

8
72


**Size**

In [ ]:
print(a.size)

9


2D Indexing

In [ ]:
a3 = np.arange(12).reshape(3,4)
print(a3)
print(a3[1,0])
print(a3[0,0])
print(a3[2,0])
print(a3[0,2])
print(a3[2,2])
print(a3[1,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4
0
8
2
10
5


3D Indexing

In [ ]:
a4 = np.arange(8).reshape(2,2,2)
print(a4)
print(a4.ndim)
print(a4[1,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
6


**Slicing**

In [ ]:
print(a4[0])
print(a4[1,0,0])

[[0 1]
 [2 3]]
4


In [ ]:
print(a4[:,0,0])
print('another example')
print(a4[:,1,0])

[0 4]
another example
[2 6]


**Linear Algebra**

Dot Product

In [ ]:
q = np.array([
    [1,2],
    [3,4]
])
p = np.array([
    [5,6],
    [7,8]
])
print(np.dot(q,p))

[[19 22]
 [43 50]]


In [ ]:
q1 = np.array([
    [2,0],
    [1,3]
])
p1 = np.array([
    [1,2],
    [3,4]
])

d1 = np.dot(q1,p1)
print(d1.shape)


(2, 2)


In [ ]:
s3 = d1.reshape(1,2,2)
w3 = np.arange(8).reshape(2,2,2)
print(np.dot(s3,w3))

[[[[  8  14]
   [ 32  38]]

  [[ 28  52]
   [124 148]]]]


In [ ]:
s1 = np.random.randint(1, 10, size=8).reshape(2,2,2)
s2 = np.random.randint(1, 5, size=4).reshape(1,2,2)
print('Dot product:\n\n',np.dot(s1,s2))

Dot product:

 [[[[39 54]]

  [[27 37]]]


 [[[29 41]]

  [[26 37]]]]


**Iteration**

In [ ]:
k = np.arange(6).reshape(2,3)
print(k)
for i in k:
  print(i)
for i in np.nditer(k):
  print(i)

[[0 1 2]
 [3 4 5]]
[0 1 2]
[3 4 5]
0
1
2
3
4
5


**Transpose**

In [ ]:
print(k.T)

[[0 3]
 [1 4]
 [2 5]]


**Ravel:**
The numpy.ravel() function is used to flatten a multi-dimensional NumPy array into a one-dimensional array.

In [ ]:
print(np.ravel(k))

[0 1 2 3 4 5]


**Stacking**

numpy.vstack(tup): Stacks arrays vertically (row-wise), which is equivalent to concatenation along the first axis (axis=0). This is useful for combining arrays with the same number of columns.

In [ ]:
a4 = np.array([[1, 2], [3, 4]])
b4 = np.array([[5, 6], [7, 8]])
result = np.vstack([a4, b4])
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


numpy.hstack(tup): Stacks arrays horizontally (column-wise), equivalent to concatenation along the second axis (axis=1) for 2D arrays. This is useful for combining arrays with the same number of rows.

In [ ]:
a5 = np.array([[1, 2], [3, 4]])
b5 = np.array([[5, 6], [7, 8]])
result = np.hstack([a5, b5])
print(result)

[[1 2 5 6]
 [3 4 7 8]]


**Practice**

In [ ]:
q2 = np.arange(6).reshape(6,)
q3 = np.arange(6).reshape(2,3)
print('1D: ',q2)
print('2D: ',q3)

1D:  [0 1 2 3 4 5]
2D:  [[0 1 2]
 [3 4 5]]


In [ ]:
f1 = np.random.randint(1, 10, size=4).reshape(1,2,2)
w2 = np.random.randint(1, 10, size=4).reshape(1,2,2)
r1 = np.dot(f1,w2)
print('Dot product: ', r1)
print('Transpose: ',r1.T)
print('Ravel: ', np.ravel(r1))
print('Slicing: ', r1[:,0,0])
print('Shape: ', r1.shape)
print('Dimension: ', r1.ndim)
print('Itemsize: ', r1.itemsize)
print('Size: ', r1.size)
print('vstack: ',np.vstack([f1, w2]))
print('hstack: ',np.hstack([f1, w2]))


Dot product:  [[[[80 70]]

  [[44 44]]]]
Transpose:  [[[[80]
   [44]]]


 [[[70]
   [44]]]]
Ravel:  [80 70 44 44]
Slicing:  [[80 70]]
Shape:  (1, 2, 1, 2)
Dimension:  4
Itemsize:  8
Size:  4
vstack:  [[[8 6]
  [4 4]]

 [[7 2]
  [4 9]]]
hstack:  [[[8 6]
  [4 4]
  [7 2]
  [4 9]]]
