In [4]:
import numpy as np

##### 1D array as vector
##### 2D array as matrix
##### 3D array as tendor

In [26]:
a = np.array([
    [[1,2,3]],
    [[1,2,3]]
])
print(f"Dimension: {a.ndim}\nShape:{a.shape}")

Dimension: 3
Shape:(2, 1, 3)


In [20]:
a

array([[[1, 2, 3],
        [2, 5, 6]],

       [[1, 2, 3],
        [2, 5, 6]]])

In [33]:
sudoku_game = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [35]:
# Data Type
# Print the data type of sudoku_game
print(sudoku_game.dtype)

# Change the data type of sudoku_game to int8
small_sudoku_game = sudoku_game.astype(np.int8)

# Print the data type of small_sudoku_game
print(small_sudoku_game.dtype)

int32
int8


Axis 0 is row
Axis 1 is columns

In [37]:
arr = np.array([
    [9, 1, 7],
    [3, 8, 2],
    [6, 4, 5]
])

print(np.sort(arr, axis=0))

[[3 1 2]
 [6 4 5]
 [9 8 7]]


In [39]:
import numpy as np

arr = np.array([
    [9, 1, 7],
    [3, 8, 2],
    [6, 4, 5]
])

print(np.sort(arr, axis=1))

[[1 7 9]
 [2 3 8]
 [4 5 6]]
